---
title: "R_project: Programmation et traitement statistique des données"
output: html_document
---
# Question 1: Estimateurs Non Paramétriques avec récursivité de la dérivée d'une fonction de régression non paramétrique

```{r}
N <- 10000 # sample size
alpha <- 0.3 # selected by cross validation (to check)
e_N <- function(x) {
  return((1/x^alpha))
}
h <- sapply(seq(1, N, 1), e_N) # bandwidth



# K values
# gaussian -> pnorm(x)
# quadratic -> ifelse(abs(x) <= 1, (15/16)*(1-x^2)^2), 0)
# epanechnikov -> ifelse(abs(x) <= 1, (3/4)*(1-x^2), 0)

# K prime values
# gaussian -> -(x*(1/sqrt(2*pi))*(exp(-(1/2)*x^2)
# quadratic -> ifelse(abs(x) <= 1, -(15/8)*(x)*(1-x^2), 0)
# epanechnikov -> ifelse(abs(x) <= 1, -(3/2)*(x)*(1-x^2), 0)

# estimator n°1 toolbox

h_N <- function(x) {
  return((1/N)*(sum((Y_N/h)*K((x-X_N)/h))))
}

g_N <- function(x) {
  return((1/N)*(sum((1/h)*K((x-X_N)/h))))
}

h_N_prime <- function(x) {
  return((1/N)*(sum((Y_N/h^2)*K_prime((x-X_N)/h))))
}

g_N_prime <- function(x) {
  return((1/N)*(sum((1/h^2)*K_prime((x-X_N)/h))))
}

es_n1 <- function(x) {
  return((h_N_prime(x)/g_N(x)) - (h_N(x)*g_N_prime(x))/(g_N(x))^2)
}

# estimator n°2



es_n2 <- function(x) {
  return((h_N_prime(x)/g(x)) - (h_N(x)*g_prime(x))/(g(x))^2)
}

# estimator n°3

es_n3 <- function(x) {
  return((1/N)*(sum(Y_N/(g(x)*h^2)*K_prime((x-X_N)/h)))
}

```

# Question 2: Simulations

```{r}

## Dans les graphiques -> que prennent-ils comme noyaux ? => pas un choix important
## Dans les graphiques -> que fixent-ils comme bandwidth ? => validation croisée

f <- function(x) {
  return((x+2)*sin(4*pi*x^2)+2*sin(8*pi*x))
}
f_prime <- function(x) {
  return(sin(4*pi*x^2)+8*pi*x*(x+2)*cos(4*pi*x^2) + 8*pi*cos(8*pi*x))
}

# if 1/2 < p <= 1
# then B(2p-1) if 1 => I2 if 0 => I1 or I3
# if 1 => unif(I2)
# if 0 => B(1-p) => if 1 => unif(I1), else unif(I3)

# a.s. conv checked with N = 10000
# plotting es_1, es_2, es_3 against f_prime on [0, 1]
# Epanechikov Kernel


alpha <- 0.3 # selected by cross validation (to check)
e_N <- function(x) {
  return((1/x^alpha))
}
h <- sapply(seq(1, N, 1), e_N) # bandwidth

# K values
# gaussian -> pnorm(x)
# quadratic -> ifelse(abs(x) <= 1, (15/16)*(1-x^2)^2), 0)
# epanechnikov -> ifelse(abs(x) <= 1, (3/4)*(1-x^2), 0)

# K prime values
# gaussian -> -(x*(1/sqrt(2*pi))*(exp(-(1/2)*x^2)
# quadratic -> ifelse(abs(x) <= 1, -(15/8)*(x)*(1-x^2), 0)
# epanechnikov -> ifelse(abs(x) <= 1, -(3/2)*(x)*(1-x^2), 0)


N <- 10000
eps_N <- rnorm(N, 0, 1)
X_N <- runif(N, 0, 1) # p = 1
Y_N <- f(X_N) + eps_N

g <- function(x) {
  return(1)
}
g_prime <- function(x){
  return(0)
}

K <- function(x) {
  return(ifelse(abs(x) <= 1, (3/4)*(1-x^2), 0)) 
}
K_prime <- function(x) {
  return(ifelse(abs(x) <= 1, -(3/2)*(x)*(1-x^2), 0))
}

# estimator n°1
h_N <- function(x) {
  y <- rep(NA, length(x))
  for (j in 1:length(x)) {
    y[j] <- (1/N)*(sum((Y_N/h)*K((x[j]-X_N)/h)))
  }
  return(y)
}
g_N <- function(x) {
  y <- rep(NA, length(x))
  for (j in 1:length(x)) {
    y[j] <- (1/N)*(sum((1/h)*K((x[j]-X_N)/h)))
  }
  return(y)
}
h_N_prime <- function(x) {
  y <- rep(NA, length(x))
  for (j in 1:length(x)) {
    y[j] <- (1/N)*(sum((Y_N/h^2)*K_prime((x[j]-X_N)/h)))
  }
  return(y)
}
g_N_prime <- function(x) {
  y <- rep(NA, length(x))
  for (j in 1:length(x)) {
    y[j] <- (1/N)*(sum((1/h^2)*K_prime((x[j]-X_N)/h)))
  }
  return(y)
}
es_n1 <- function(x) {
  return((h_N_prime(x)/g_N(x)) - (h_N(x)*g_N_prime(x))/(g_N(x))^2)
}

# estimator n°2
es_n2 <- function(x) {
  return((h_N_prime(x)/g(x)) - (h_N(x)*g_prime(x))/(g(x))^2)
}

# estimator n°3
es_n3 <- function(x) {
  y <- rep(NA, length(x))
  for (j in 1:length(x)) {
    y[j] <- (1/N)*(sum(Y_N/(g(x)*h^2)*K_prime((x[j]-X_N)/h)))
  }
  return(y)
}


# asymptotic normality checked at x = 0.5 and x = 0.8
# N = 2000

```

## Figure 1 (almost sure convergence)

```{r}
library(ggplot2)
x <- seq(0, 1, length.out = 10000)
df <- data.frame(
  x = rep(x, 4),
  y = c(f_prime(x), es_n1(x), es_n2(x), es_n3(x)),
  curve = factor(rep(c("Target","Estimator 1", "Estimator 2", "Estimator 3"), each = length(x)))
)
ggplot(df, aes(x = x, y = y, color = curve, linetype = curve)) +
  geom_line(size = 1.2) +
  geom_point(
    data = subset(df, curve != "Target"),
    size = 1.5,
    alpha = 0.7
  ) +
  scale_linetype_manual(values = c("Target" = "solid", "Estimator 1" = "dashed", "Estimator 2" = "dotted", "Estimator 3" = "dotdash")) +
  labs(
    title = "Customized Curves on [0, 1]",
    x = "x",
    y = "y",
    color = "Function",
    linetype = "Function"
  ) +
  theme_minimal(base_size = 14)

```

## Figure 2 (CLT)

```{r}

```

# Annexe

## Vérification des hypothèses pour les noyaux

Ajouter les vérifications


## Calculs de l'espérance et de la variance des estimateurs


$$Y_n = f(X_n) + \epsilon_n, X_n \perp \epsilon_n, X_n \perp X_k (k \neq n), P(X_k \in B) = P(X_n \in B), B \in \mathbf{B}(\mathbf{R}), E(\epsilon) = 0, E(\epsilon^2) = \sigma^2, g \in C_b(X) $$
## Estimateur 1

$$ \left\{
    \begin{array}{ll}
       E[\hat{f}(x)] =  \\
       Var(\hat{f}(x)) =
    \end{array}
\right.$$


## Estimateur 2

$$ \left\{
    \begin{array}{ll}
       E[\tilde{f}(x)] =  \\
       Var(\tilde{f}(x)) =
    \end{array}
\right.$$


## Estimateur 3

$$ \left\{
    \begin{array}{ll}
       E[\overset{\vee}{f}(x)] = \frac{1}{n}\sum_{k=1}^n \frac{1}{h_k}E[\frac{f(X_k)}{g(X_k)}K(\frac{x-X_k}{h_k})]   \\
       
       Var(\overset{\vee}{f}(x)) =
    \end{array}
\right.$$